version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - '5832:5432' # expose pg on port 5832 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
